---
abstract: 'Open Source Shop Machine'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nitesi
no_index:
  directory:
    - t
    - inc
requires:
  ACL::Lite: 0.0002
  Crypt::Password: 0.23
  Data::SimplePassword: 0
  Moo: 0.091004
  MooX::Types::MooseLike: 0.16
  Test::More: 0
resources:
  repository: https://github.com/racke/Nitesi
version: 0.0080
